In [299]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn.metrics import multilabel_confusion_matrix,classification_report


In [248]:
senti_csv = pd.read_csv("sentiment_csv.csv")
ibm_csv = pd.read_csv("IBM.csv")

In [249]:
senti_csv['real_score'].unique()

array([ 1., -1., nan,  0.])

In [250]:
ibm_csv.head()

user             time  \
0  Vanprobsolution  10/5/2020 20:51   
1  Vanprobsolution  10/5/2020 20:50   
2  Vanprobsolution  10/5/2020 19:51   
3  Vanprobsolution  10/5/2020 19:50   
4  Vanprobsolution  10/5/2020 16:51   

                                                text  favourite_count  \
0  rt : in as much as you eat daily, it becomes m...                0   
1  rt : thank you, , for sharing how our new entr...                0   
2  rt : food safety culture starts with the hirin...                0   
3  rt : adulteration concerns rise along with cur...                0   
4  rt : did you know children under five are most...                0   

   retweet_count lang                                        description  \
0              3   en  New Technology Products for #Food #Pharma #Ret...   
1              1   en  New Technology Products for #Food #Pharma #Ret...   
2              1   en  New Technology Products for #Food #Pharma #Ret...   
3              2   en  New Technology Products for #Food #Pharma #Ret...   
4             12   en  New Technology Products for #Food #Pharma #Ret...   

  country tweet_type user_type  ibm_score  
0      NG         RT         o   0.385358  
1      NG         RT         o   0.991698  
2      NG         RT         o   0.000000  
3      NG         RT         o   0.000000  
4      NG         RT         o  -0.834673

In [279]:
round(-0.99,2) < 0

True

In [227]:
def polarity_score(x):
    if round(x,2) ==0.0:
        return 2
    elif round(x,2) >0:
        return 3
    elif round(x,2)<0:
        return 1

In [280]:
ibm_csv["ibm_polarity_score"]=ibm_csv['ibm_score'].apply(polarity_score)

In [281]:
ibm_csv['ibm_polarity_score'].unique()

array([3, 2, 1])

In [283]:
senti_csv["vander_polarity_score"] =senti_csv["vader_score"].apply(polarity_score)

In [284]:
senti_csv['textblob_polarity_score'] = senti_csv["textblob"].apply(polarity_score)

In [286]:
senti_csv["real_score"] = senti_csv["real_score"].apply(lambda x:round(x,1))

In [287]:
senti_csv['real_score'].unique()

array([ 3.,  1., nan,  2.])

In [288]:
senti_csv['real_score'].isnull().sum()

5483

In [265]:
def hello(x):
    if x ==1.0:
        return 3
    elif x ==0.0:
        return 2
    elif x <0.0:
        return 1
    else:
        return np.nan

In [266]:
senti_csv['real_score'] = senti_csv["real_score"].apply(hello)

In [268]:
senti_csv['real_score'].unique()

array([ 3.,  1., nan,  2.])

In [289]:
joined = ibm_csv.loc[:,["user",'ibm_polarity_score']]

In [290]:
len(joined)

5531

In [291]:
joined_csv = pd.concat([senti_csv,joined],axis=1)

In [292]:
len(joined_csv)

5531

In [273]:
joined_csv.head()

user             time  \
0  Vanprobsolution  10/5/2020 20:51   
1  Vanprobsolution  10/5/2020 20:50   
2  Vanprobsolution  10/5/2020 19:51   
3  Vanprobsolution  10/5/2020 19:50   
4  Vanprobsolution  10/5/2020 16:51   

                                                text  favourite_count  \
0  rt : in as much as you eat daily, it becomes m...                0   
1  rt : thank you, , for sharing how our new entr...                0   
2  rt : food safety culture starts with the hirin...                0   
3  rt : adulteration concerns rise along with cur...                0   
4  rt : did you know children under five are most...                0   

   retweet_count lang                                        description  \
0              3   en  New Technology Products for #Food #Pharma #Ret...   
1              1   en  New Technology Products for #Food #Pharma #Ret...   
2              1   en  New Technology Products for #Food #Pharma #Ret...   
3              2   en  New Technology Products for #Food #Pharma #Ret...   
4             12   en  New Technology Products for #Food #Pharma #Ret...   

  country tweet_type user_type  vader_score  textblob  vander_polarity_score  \
0      NG         RT         o       0.4939  0.233333                      3   
1      NG         RT         o       0.8834  0.568182                      3   
2      NG         RT         o       0.4215  0.000000                      3   
3      NG         RT         o       0.4767  0.000000                      3   
4      NG         RT         o      -0.4005 -0.041667                      1   

   textblob_polarity_score  real_score             user  ibm_polarity_score  
0                        3         3.0  Vanprobsolution                   3  
1                        3         3.0  Vanprobsolution                   3  
2                        2         3.0  Vanprobsolution                   2  
3                        2         1.0  Vanprobsolution                   2  
4                        1         1.0  Vanprobsolution                   1

In [274]:
len(joined_csv)

5531

In [293]:
another_df = joined_csv.copy()
#another_df["real_empty"] = another_df['real_score'].apply(lambda x: x if type(x)==int  else np.nan)

In [298]:
another_df.isnull().sum()

user                       0
time                       0
text                       0
favourite_count            0
retweet_count              0
lang                       0
description                0
country                    0
tweet_type                 0
user_type                  0
vader_score                0
textblob                   0
vander_polarity_score      0
textblob_polarity_score    0
real_score                 0
user                       0
ibm_polarity_score         0
dtype: int64

In [295]:
another_df.dropna(subset=["real_score"],inplace=True)

In [297]:
another_df["real_score"] = another_df["real_score"].astype(np.int)

In [109]:
another_df

int

In [149]:
another_df['real_score'] = another_df["real_score"].apply(lambda x: int(x))

In [115]:
type(-1)

int

In [116]:
another_df['real_score'].unique()

array([ 1, -1])

In [156]:
another_df=another_df.reset_index(dbrop=True)

In [306]:
def class_report(senti,real_score):
    for i in senti:
        print("***********classification report for {}****************".format(i))
        print()
        print(classification_report(list(another_df[real_score]),list(another_df[i]),labels=[3,2,1]))
        print('*********************************************************')
        print()
    

In [159]:
another_df[0:2]

user             time  \
0  Vanprobsolution  10/5/2020 20:51   
1  Vanprobsolution  10/5/2020 20:50   

                                                text  favourite_count  \
0  rt : in as much as you eat daily, it becomes m...                0   
1  rt : thank you, , for sharing how our new entr...                0   

   retweet_count lang                                        description  \
0              3   en  New Technology Products for #Food #Pharma #Ret...   
1              1   en  New Technology Products for #Food #Pharma #Ret...   

  country tweet_type user_type  vader_score  textblob  vander_polarity_score  \
0      NG         RT         o       0.4939  0.233333                      1   
1      NG         RT         o       0.8834  0.568182                      1   

   textblob_polarity_score  real_score             user  ibm_polarity_score  
0                        1           1  Vanprobsolution                   1  
1                        1           1  Vanprobsolution                   1

In [160]:
print(another_df["real_score"])

0     1
1     1
2     1
3    -1
4    -1
5     1
6     1
7     0
8    -1
9     0
10    0
11    0
12    1
13    0
14    1
15    1
16   -1
17    1
18   -1
19    1
20   -1
21   -1
22    1
23    1
24    0
25   -1
26    0
27    0
28   -1
29    1
30    1
31   -1
32   -1
33    1
34   -1
35   -1
36    1
37   -1
38    0
39    1
40    1
41    1
42   -1
43   -1
44   -1
45   -1
46   -1
47   -1
Name: real_score, dtype: int64


In [161]:
print(another_df["ibm_polarity_score"])

0     1
1     1
2     0
3     0
4    -1
5     1
6     0
7     1
8     1
9    -1
10    0
11    1
12    1
13    1
14    1
15    0
16   -1
17    1
18    1
19    0
20   -1
21    1
22   -1
23    1
24    0
25    0
26    0
27    0
28   -1
29    1
30    1
31    1
32   -1
33    1
34   -1
35   -1
36    0
37   -1
38   -1
39    1
40    1
41    1
42   -1
43   -1
44   -1
45   -1
46   -1
47   -1
Name: ibm_polarity_score, dtype: int64


In [80]:
print(another_df.isnull().sum())

user                       0
time                       0
text                       0
favourite_count            0
retweet_count              0
lang                       0
description                0
country                    0
tweet_type                 0
user_type                  0
vader_score                0
textblob                   0
vander_polarity_score      0
textblob_polarity_score    0
real_score                 0
user                       0
ibm_polarity_score         0
real_empty                 0
dtype: int64


In [158]:
print(len(another_df['real_score']))
print(len(another_df["ibm_polarity_score"]))

48
48


In [307]:
class_report(senti=["ibm_polarity_score","vander_polarity_score","textblob_polarity_score"],real_score="real_score")

***********classification report for ibm_polarity_score****************

              precision    recall  f1-score   support

           3       0.65      0.68      0.67        19
           2       0.36      0.44      0.40         9
           1       0.82      0.70      0.76        20

    accuracy                           0.65        48
   macro avg       0.61      0.61      0.61        48
weighted avg       0.67      0.65      0.65        48

*********************************************************

***********classification report for vander_polarity_score****************

              precision    recall  f1-score   support

           3       0.51      0.95      0.67        19
           2       0.50      0.22      0.31         9
           1       1.00      0.45      0.62        20

    accuracy                           0.60        48
   macro avg       0.67      0.54      0.53        48
weighted avg       0.71      0.60      0.58        48

******************************